# Generated by Django 3.2.9 on 2021-11-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_answer_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_accepted_answer',
            field=models.BooleanField(default=False),
        ),
    ]
